# "main.py" generated by Pyrustic Manager
from pyrustic.app import App
from hubstore.view.main_view import MainView
from hubstore.misc import my_theme


def main():
    # The App
    app = App(__package__)
    app.root.title("Hubstore - built with Pyrustic")
    # Set theme
    app.theme = my_theme.get_theme()
    # Set view
    app.view = lambda: MainView(app)
    # Center the window
    app.center()
    # Lift off !
    app.start()


if __name__ == "__main__":
    main()
