# "main.py" generated by Pyrustic Manager
from pyrustic.app import App
from hubstore.view.main_view import MainView
from hubstore.misc import my_theme


def main():
    # The App
    app = App()
    # Title
    app.title = "Hubstore"
    # Geometry
    app.geometry = "900x550+0+0"
    # Resizable
    app.resizable = (False, False)
    # Set theme
    app.theme = my_theme.get_theme()
    # Set view
    app.view = MainView(app)
    # Center the window
    app.center()
    # Lift off !
    app.start()


if __name__ == "__main__":
    main()
